# Generated by Django 5.2.2 on 2025-06-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='estado',
            field=models.CharField(choices=[('NM', 'Como Nueva'), ('EX', 'Excelente'), ('LP', 'Poco Jugada'), ('MP', 'Medianamente jugada'), ('HP', 'Muy jugada'), ('DMG', 'Dañada')], default='NM', max_length=4),
        ),
    ]
