# Generated by Django 5.2.2 on 2025-06-05 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0003_carta_usuario_alter_carta_estado_carpeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='cartas.carpeta'),
        ),
    ]
