# Generated by Django 5.2.2 on 2025-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0004_alter_carta_carpeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'ordering': ['-fecha_agregada']},
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='fecha_publicacion',
            new_name='fecha_agregada',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='carpeta',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='carta',
            name='en_venta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carta',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés'), ('JP', 'Japonés'), ('FR', 'Francés')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carta',
            name='juego',
            field=models.CharField(choices=[('MTG', 'Magic: The Gathering'), ('PKMN', 'Pokémon'), ('YGO', 'Yu-Gi-Oh!'), ('DGM', 'Digimon'), ('DBS', 'Dragon Ball Super'), ('OPC', 'One Piece'), ('MYL', 'Mitos y Leyendas')], default='es', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carta',
            name='rareza',
            field=models.CharField(choices=[('C', 'Común'), ('U', 'Incomún'), ('R', 'Rara'), ('M', 'Mítica'), ('SP', 'Especial')], default='comun', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carta',
            name='vendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carta',
            name='edicion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carta',
            name='estado',
            field=models.CharField(choices=[('NM', 'Near Mint'), ('PL', 'Played'), ('DM', 'Damaged')], max_length=2),
        ),
        migrations.AlterField(
            model_name='carta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
