# Generated by Django 5.2.2 on 2025-06-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0005_alter_carta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
